Added compiler profiles. Fixed bugs.

diff --git a/disttest/disttest b/disttest/disttest
--- a/disttest/disttest
+++ b/disttest/disttest
@@ -10,20 +10,20 @@ TESTBASE_DIR=/tmp/yapet-disttest
 TESTLOGS_DIR=${TESTBASE_DIR}/logs
 TESTBUILD_DIR=${TESTBASE_DIR}/build
 TESTINST_DIR=${TESTBASE_DIR}/inst
+
 #
-# Used in case compiler profile does not specify ${MAKE}
+# May be overwritten in compiler profiles
 #
-MYMAKE=gmake
 CONFCOMMONOPTS="--prefix=${TESTINST_DIR} --with-docbook-xsl=/opt/guengel/share/docbook/xsl"
 #
 # The enables that will be toggled to test the dists
 #
-#CONFENABLES="--enable-assert --enable-build-doc --enable-install-doc --enable-source-doc --enable-terminal-title --enable-csv2yapet --enable-pwgen --enable-nls --enable-threads"
-CONFENABLES="--enable-foo --enable-bar"
+CONFENABLES="--enable-assert --enable-build-doc --enable-install-doc --enable-source-doc --enable-terminal-title --enable-csv2yapet --enable-pwgen --enable-nls --enable-threads"
+#CONFENABLES="--enable-foo --enable-bar"
 
 #
 # Set this in the compiler.profiles
-# 
+#
 NUMCOMPILERPROFILES=0
 #
 # These WILL BE unset before each compiler profile is loaded!!!
@@ -40,7 +40,7 @@ GLOBALLOGFILE=${TESTBASE_DIR}/testlog-${DATESTARTED}
 MAKETARGETS=(all check clean)
 
 COMPILERPROFILES=""
-if [ ! -z "$2" && -f "$2" ]
+if [ ! -z "$2" -a -f "$2" ]
 then
     COMPILERPROFILES=$2
 else
@@ -54,6 +54,22 @@ else
 fi
 # Suck in the compiler profiles
 . ${COMPILERPROFILES}
+
+#
+# Used in case compiler profile does not specify ${MAKE}
+#
+MYMAKE=`which gmake`
+
+SEQ=`which gseq 2>/dev/null`
+if [ $? -ne 0 ]
+then
+    SEQ=`which seq 2>/dev/null`
+    if [ $? -ne 0 ]
+    then
+	echo "Unable to find (g)seq... Aborting."
+	exit 1
+    fi
+fi
 
 cmdhelp() {
     echo "disttest <pathtosource> [<compilerprofile>]";
@@ -111,7 +127,7 @@ logenv () {
 clearenv () {
     for ev in ${ENVVARSUSED}
     do
-	usnet ${ev}
+	unset ${ev}
     done
 
     # reset the path again
@@ -153,7 +169,7 @@ cleantestbuild () {
 # arguments are interpreted as --enable flags to configure.
 #
 # There must be at least two arguments
-# 
+#
 testbuild () {
     if [ $# -lt 2 ]
     then
@@ -188,7 +204,7 @@ testbuild () {
     fi
     local numtargets=`echo ${MAKETARGETS[*]} | wc -w `
     let $((numtargets--))
-    for targetno in `seq 0 ${numtargets}`
+    for targetno in `${SEQ} 0 ${numtargets}`
     do
 	local target=${MAKETARGETS[${targetno}]}
 	echo "* Building ${logfile_prefix} target ${target}"
@@ -207,12 +223,12 @@ NUMENABLES=`echo "${CONFENABLES}" | wc -w`
 
 logglobal "- Started"
 
-for cpno in `seq 1 ${NUMCOMPILERPROFILES}`
+for cpno in `${SEQ} 1 ${NUMCOMPILERPROFILES}`
 do
     logglobal "- Loading Compiler Profile ${cpno}"
     compilerprofile_${cpno}
     logenv ${TESTLOGS_DIR}/compilerprof${cpno}-env
-    for i in `seq 1 ${NUMENABLES}`
+    for i in `${SEQ} 1 ${NUMENABLES}`
     do
 	logglobal "- Starting test run $i using compiler profile ${cpno}"
 
@@ -226,7 +242,7 @@ do
 	    else
 		logglobal ":( compilerprof${cpno}-subtest1-run${i}: error in make ${MAKETARGET[$retval]}"
 	    fi
-	else 
+	else
 	    logglobal ":) compilerprof${cpno}-subtest1-run${i}: Success"
 	fi
 	cd ${CWD}
@@ -242,7 +258,7 @@ do
 	    else
 		logglobal ":( compilerprof${cpno}-subtest2-run${i}: error in make ${MAKETARGET[$retval]}"
 	    fi
-	else 
+	else
 	    logglobal ":) compilerprof${cpno}-subtest2-run${i}: Success"
 	fi
 	cd ${CWD}
@@ -258,14 +274,14 @@ do
 	    else
 		logglobal ":( compilerprof${cpno}-subtest3-run${i}: error in make ${MAKETARGET[$retval]}"
 	    fi
-	else 
+	else
 	    logglobal ":) compilerprof${cpno}-subtest3-run${i}: Success"
 	fi
 	cd ${CWD}
 	cleantestbuild
 
     done
-    globallog "- Clear Environment for Compiler Profile ${cpno}"
+    logglobal "- Clear Environment for Compiler Profile ${cpno}"
     clearenv
 done
 
